'use strict';

var CONSTANT = {
	TILE_SIZE:  24,

	BLOCK_GREEN:  1,
	BLOCK_BLUE:   2,
	BLOCK_RED:    3,
	BLOCK_PURPLE: 4,
	BLOCK_BROWN:  5,
	LADDER:       6,
	PLAYER:       7,
	ENEMY:        8,
	ITEM:         9,
	DEATH:       10,
	BLOCK_STONE1:11,
	BLOCK_STONE2:12,
	BLOCK_STONE3:13,


	STATE_NORMAL:    1,
	STATE_CLIMBDOWN: 2,
	STATE_DYING:     3,
	STATE_EXCHANGE:  4,
	STATE_FALLDOWN:  5,
};

// レンダリングの順番
// 上にあるものほど奥に描画／下にあるものほど手前に描画
CONSTANT.RENDER_SORT = [
	CONSTANT.BLOCK_GREEN,
	CONSTANT.BLOCK_BLUE,
	CONSTANT.BLOCK_RED,
	CONSTANT.BLOCK_PURPLE,
	CONSTANT.BLOCK_BROWN,
	CONSTANT.BLOCK_STONE1,
	CONSTANT.BLOCK_STONE2,
	CONSTANT.BLOCK_STONE3,
	CONSTANT.DEATH,
	CONSTANT.LADDER,
	CONSTANT.ENEMY,
	CONSTANT.PLAYER,
	CONSTANT.ITEM,
];


module.exports = CONSTANT;
