'use strict';
var DEBUG = require("./debug_constant");

var CONSTANT = {
	DEBUG: {},

	// スコアの最高数
	MAX_SCORE:  3,

	// Ex Story の開始 stage no
	EX_STORY_START_STAGE_NO:  31,

	// ステージ上のタイルのサイズ
	TILE_SIZE:  24,

	// ステージの、画面上の表示開始位置
	STAGE_OFFSET_X: 25,
	STAGE_OFFSET_Y: 50,

	// ステージの縦 横のタイル数
	STAGE_TILE_X_NUM: 30,
	STAGE_TILE_Y_NUM: 20,

	// ステージ上のタイルの種類
	BLOCK_GREEN:     1,
	BLOCK_BLUE:      2,
	BLOCK_RED:       3,
	BLOCK_PURPLE:    4,
	BLOCK_BROWN:     5,
	LADDER:          6,
	PLAYER:          7,
	ENEMY:           8,
	ITEM_FOR_REIMU:  9,
	DEATH:           10,
	BLOCK_STONE1:    11,
	BLOCK_STONE2:    12,
	BLOCK_STONE3:    13,
	ITEM_FOR_YUKARI: 14,
	ITEM_OF_EXCHANGE:15,
	ENEMY_VERTICAL:  16,


	// プレイヤーの状態
	STATE_NORMAL:    1,
	STATE_CLIMBDOWN: 2,
	STATE_DYING:     3,
	STATE_EXCHANGE:  4,
	STATE_FALLDOWN:  5,
	STATE_MOVELEFT:  6,
	STATE_MOVERIGHT: 7,


	// キャラ ドット絵一覧
	REIMU_NO:    1, // 霊夢(実体)
	YUKARI_NO:   2, // 紫
	EX_REIMU_NO: 3, // 霊夢(精神)
};

// レンダリングの順番
// 上にあるものほど奥に描画／下にあるものほど手前に描画
CONSTANT.RENDER_SORT = [
	CONSTANT.BLOCK_GREEN,
	CONSTANT.BLOCK_BLUE,
	CONSTANT.BLOCK_RED,
	CONSTANT.BLOCK_PURPLE,
	CONSTANT.BLOCK_BROWN,
	CONSTANT.BLOCK_STONE1,
	CONSTANT.BLOCK_STONE2,
	CONSTANT.BLOCK_STONE3,
	CONSTANT.DEATH,
	CONSTANT.LADDER,
	CONSTANT.ENEMY,
	CONSTANT.ENEMY_VERTICAL,
	CONSTANT.PLAYER,
	CONSTANT.ITEM_FOR_REIMU,
	CONSTANT.ITEM_FOR_YUKARI,
	CONSTANT.ITEM_OF_EXCHANGE,
];

if (DEBUG.ON) {
	CONSTANT.DEBUG = DEBUG;
}
module.exports = CONSTANT;
